// src/constants/permissions.js

const PERMISSIONS = {

  // Dashboard
  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  // Study Management
  VIEW_STUDIES: "VIEW_STUDIES",
  CREATE_STUDY: "CREATE_STUDY",
  EDIT_STUDY: "EDIT_STUDY",
  DELETE_STUDY: "DELETE_STUDY",

  // Subjects
  VIEW_SUBJECTS: "VIEW_SUBJECTS",
  CREATE_SUBJECT: "CREATE_SUBJECT",
  EDIT_SUBJECT: "EDIT_SUBJECT",
  DELETE_SUBJECT: "DELETE_SUBJECT",

  // Visits
  VIEW_VISITS: "VIEW_VISITS",
  CREATE_VISIT: "CREATE_VISIT",
  EDIT_VISIT: "EDIT_VISIT",
  COMPLETE_VISIT: "COMPLETE_VISIT",

  // Screening
  VIEW_SCREENING: "VIEW_SCREENING",
  CREATE_SCREENING: "CREATE_SCREENING",

  // Enrollment
  VIEW_ENROLLMENT: "VIEW_ENROLLMENT",
  CREATE_ENROLLMENT: "CREATE_ENROLLMENT",

  // Randomization
  VIEW_RANDOMIZATION: "VIEW_RANDOMIZATION",

  // Site Activities
  VIEW_SITE_ACTIVITIES: "VIEW_SITE_ACTIVITIES",

  // Monitoring
  VIEW_MONITORING: "VIEW_MONITORING",

  // Regulatory Documents
  VIEW_REGULATORY_DOCS: "VIEW_REGULATORY_DOCS",
  APPROVE_REGULATORY_DOCS: "APPROVE_REGULATORY_DOCS",

  // Comments (renamed from Queries)
  VIEW_COMMENTS: "VIEW_COMMENTS",
  CREATE_COMMENT: "CREATE_COMMENT",
  RESOLVE_COMMENT: "RESOLVE_COMMENT",
  // UPDATED: legacy permission keys retained for backward compatibility
  VIEW_QUERIES: "VIEW_COMMENTS",
  CREATE_QUERY: "CREATE_COMMENT",
  RESOLVE_QUERY: "RESOLVE_COMMENT",

  // Reports
  VIEW_REPORTS: "VIEW_REPORTS",
  EXPORT_REPORTS: "EXPORT_REPORTS",

  // User Management
  VIEW_USERS: "VIEW_USERS",
  CREATE_USER: "CREATE_USER",
  EDIT_USER: "EDIT_USER",
  DELETE_USER: "DELETE_USER",

  // Settings
  VIEW_SETTINGS: "VIEW_SETTINGS",
  EDIT_SETTINGS: "EDIT_SETTINGS",
};

export default PERMISSIONS;