import ROLES from "../constants/roles";
import PERMISSIONS from "../constants/permissions";

const rolePermissions = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.SITE_STAFF]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDIES,
    PERMISSIONS.VIEW_SUBJECTS,
    PERMISSIONS.CREATE_SUBJECT,
    PERMISSIONS.EDIT_SUBJECT,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.CREATE_VISIT,
    PERMISSIONS.EDIT_VISIT,
    PERMISSIONS.COMPLETE_VISIT,
    PERMISSIONS.VIEW_SCREENING,
    PERMISSIONS.CREATE_SCREENING,
    PERMISSIONS.VIEW_ENROLLMENT,
    PERMISSIONS.CREATE_ENROLLMENT,
    PERMISSIONS.VIEW_COMMENTS,
    PERMISSIONS.CREATE_COMMENT,
    PERMISSIONS.VIEW_SITE_ACTIVITIES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_SETTINGS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_REGULATORY_DOCS
  ],

  [ROLES.PI]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDIES,
    PERMISSIONS.VIEW_SUBJECTS,
    PERMISSIONS.CREATE_SUBJECT,
    PERMISSIONS.EDIT_SUBJECT,
    PERMISSIONS.DELETE_SUBJECT,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.VIEW_COMMENTS,
    PERMISSIONS.CREATE_COMMENT,
    PERMISSIONS.RESOLVE_COMMENT,
    PERMISSIONS.VIEW_REGULATORY_DOCS,
    PERMISSIONS.APPROVE_REGULATORY_DOCS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SETTINGS,
    PERMISSIONS.EDIT_SETTINGS
  ],

  [ROLES.CRO]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDIES,
    PERMISSIONS.CREATE_STUDY,
    PERMISSIONS.VIEW_SUBJECTS,
    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.VIEW_COMMENTS,
    PERMISSIONS.CREATE_COMMENT,
    PERMISSIONS.VIEW_MONITORING,
    PERMISSIONS.VIEW_REGULATORY_DOCS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_SETTINGS
  ],

  [ROLES.SPONSOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_STUDIES,
    PERMISSIONS.CREATE_STUDY,
    PERMISSIONS.VIEW_SUBJECTS,
    PERMISSIONS.VIEW_COMMENTS,
    PERMISSIONS.CREATE_COMMENT,
    PERMISSIONS.VIEW_REGULATORY_DOCS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_SETTINGS
  ]
};

export default rolePermissions;
