// src/utils/rolePermissions.js

import ROLES from "../constants/roles";
import PERMISSIONS from "../constants/permissions";

const rolePermissions = {

  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.SITE_STAFF]: [

    PERMISSIONS.VIEW_DASHBOARD,

    PERMISSIONS.VIEW_STUDIES,

    PERMISSIONS.VIEW_SUBJECTS,
    PERMISSIONS.CREATE_SUBJECT,
    PERMISSIONS.EDIT_SUBJECT,

    PERMISSIONS.VIEW_VISITS,
    PERMISSIONS.CREATE_VISIT,
    PERMISSIONS.EDIT_VISIT,
    PERMISSIONS.COMPLETE_VISIT,

    PERMISSIONS.VIEW_SCREENING,
    PERMISSIONS.CREATE_SCREENING,

    PERMISSIONS.VIEW_ENROLLMENT,
    PERMISSIONS.CREATE_ENROLLMENT,

    PERMISSIONS.VIEW_QUERIES,
    PERMISSIONS.CREATE_QUERY,

    PERMISSIONS.VIEW_SITE_ACTIVITIES,
  ],

};

export default rolePermissions;